spring:
  application:
    name: flight_booking
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/flight_booking
    username: postgres
    password: vvv2002tb
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 9023
